"""add claims_analytics_export table

Revision ID: 49e552015530
Revises: ded0b615465a
Create Date: 2026-08-13 10:02:48.393404

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "49e552015530"
down_revision: str | Sequence[str] | None = "ded0b615465a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "claims_analytics_export",
        sa.Column("export_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("claim_number", sa.String(length=100), nullable=True),
        sa.Column("policy_number", sa.String(length=100), nullable=True),
        sa.Column("document_type", sa.String(length=50), nullable=False),
        sa.Column("incident_date", sa.Date(), nullable=True),
        sa.Column("filing_date", sa.Date(), nullable=True),
        sa.Column("claimed_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("fraud_score", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("fraud_status", sa.String(length=30), nullable=True),
        sa.Column("inconsistency_count", sa.Integer(), nullable=False),
        sa.Column("confirmed_by", sa.UUID(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "exported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("export_id"),
        sa.UniqueConstraint("document_id"),
    )
    op.create_index(
        op.f("ix_claims_analytics_export_claim_number"),
        "claims_analytics_export",
        ["claim_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_claims_analytics_export_policy_number"),
        "claims_analytics_export",
        ["policy_number"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_claims_analytics_export_policy_number"), table_name="claims_analytics_export"
    )
    op.drop_index(
        op.f("ix_claims_analytics_export_claim_number"), table_name="claims_analytics_export"
    )
    op.drop_table("claims_analytics_export")
    # ### end Alembic commands ###
